language: go

script:
- go get github.com/aktau/github-release
- github-release --help
- mkdir runsc ; cd runsc
- curl -O https://github.com/google/gvisor-containerd-shim/releases/download/v${RUNSC_CONTAINERD_VERSION}/containerd-shim-runsc-v1.linux-amd64
- curl -O https://storage.googleapis.com/gvisor/releases/nightly/latest/runsc
- chmod +x containerd-shim-runsc-v1.linux-amd64 runsc
- export FILE_NAME="runsc-$(go env GOOS)-$(go env GOARCH)"
- cd .. ; tar -zcvf ${FILE_NAME}.tar.gz runsc
- github-release upload --user khs1994-docker --repo gvisor-mirror --tag nightly --name "${FILE_NAME}.tar.gz" --file "${FILE_NAME}.tar.gz" -R

env:
  global:
    RUNSC_CONTAINERD_VERSION=0.0.3
