language: go

script:
- go get github.com/aktau/github-release
- github-release --help
- mkdir runsc ; cd runsc
- curl -Lo containerd-shim-runsc-v1 https://storage.googleapis.com/gvisor/releases/master/latest/containerd-shim-runsc-v1
- curl -Lo gvisor-containerd-shim   https://storage.googleapis.com/gvisor/releases/master/latest/gvisor-containerd-shim
- curl -LO                          https://storage.googleapis.com/gvisor/releases/master/latest/runsc
#                                   https://storage.googleapis.com/gvisor/releases/release/20200914.0/runsc
#                                   https://storage.googleapis.com/gvisor/releases/release/latest/runsc
#                                   https://storage.googleapis.com/gvisor/releases/master/latest/runsc
- chmod +x gvisor-containerd-shim containerd-shim-runsc-v1 runsc
- export FILE_NAME="runsc-$(go env GOOS)-$(go env GOARCH)"
- tar -zcvf ${FILE_NAME}.tar.gz gvisor-containerd-shim containerd-shim-runsc-v1 runsc
- github-release upload --user khs1994-docker --repo gvisor-mirror --tag nightly --name "${FILE_NAME}.tar.gz" --file "${FILE_NAME}.tar.gz" -R

env:
  global:
    - RUNSC_VERSION=latest
