on:
  push

jobs:
  ci:
    runs-on: ubuntu
    steps:
    - run: |
        go get github.com/aktau/github-release
        github-release --help
        mkdir runsc ; cd runsc
        curl -Lo containerd-shim-runsc-v1 https://storage.googleapis.com/gvisor/releases/master/latest/x86_64/containerd-shim-runsc-v1
        curl -LO                          https://storage.googleapis.com/gvisor/releases/master/latest/x86_64/runsc
# https://gvisor.dev/docs/user_guide/install/
#                                   https://storage.googleapis.com/gvisor/releases/release/20200914.0/x86_64/runsc
#                                   https://storage.googleapis.com/gvisor/releases/release/latest/x86_64/runsc
#                                   https://storage.googleapis.com/gvisor/releases/master/latest/x86_64/runsc
#                                   https://storage.googleapis.com/gvisor/releases/nightly/latest/x86_64/runsc
        chmod +x containerd-shim-runsc-v1 runsc
        export FILE_NAME="runsc-$(go env GOOS)-$(go env GOARCH)"
        tar -zcvf ${FILE_NAME}.tar.gz containerd-shim-runsc-v1 runsc
        github-release upload --user khs1994-docker --repo gvisor-mirror --tag nightly --name "${FILE_NAME}.tar.gz" --file "${FILE_NAME}.tar.gz" -R

env:
  RUNSC_VERSION: latest
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
